### ISSUE TITLE
Problems with Bootstrap 3.3.7 [class*="row"]

### ISSUE THREAD

**Issue by paavo** [jonnitto/Jonnitto.ImagesInARow#1]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### Problem
class="jonnitto-imagesinarow__row" accidentally act's as Bootstrap .row because of the _.container-fluid [class*="row"]_ selector. 

### Solution
A: Remove **row** from Classname "jonnitto-imagesinarow__row". 
B: Use a configurable variable as classname

**Comment by jonnitto** [comment]
Hi @drlimbo 
Thank you for your issue. If I look at the source code of the [Bootstrap CSS](https://github.com/twbs/bootstrap/blob/v3.3.7/dist/css/bootstrap.css), I can't find a class like this. It looks like you add this by yourself. You should change the selector to `.container-fluid .row`

**Comment by paavo** [comment]
im sorry @jonnitto!
looks like my co-worker added the code and i thought its coming from bootstrap..

**Comment by jonnitto** [comment]
No problem. I recently released Version 1.1: Much smaller CSS footprint
